"""Add deleted_at columns

Revision ID: 42b5093f9660
Revises: 2e7ad6157118
Create Date: 2025-04-22 02:30:04.049162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b5093f9660'
down_revision = '2e7ad6157118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
